You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: value.bets[i].join is not a function
    at results.forEach (/root/xien5-api/controller/email_bet.controller.js:60:50)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:8846) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: value.bets[i].join is not a function
(node:8846) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8846) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: value.bets[i].join is not a function
(node:8846) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: value.bets[i].join is not a function
(node:8846) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: value.bets[i].join is not a function
